package mobi.mymem.oa;

import mobi.mymem.MyContextVariables;

import org.morfeo.tidmobile.server.oa.BasicApplicationOperation;
import org.morfeo.tidmobile.server.oa.OAException;
import org.morfeo.tidmobile.context.Context;

/* Java code generated by MyMobileWeb Plugin */
public class Center extends BasicApplicationOperation {


@Override
public void execute(Context the_context) throws OAException {
 
	the_context.removeElement(MyContextVariables.LATITUDE);
	the_context.removeElement(MyContextVariables.LONGITUDE);
}

}