package mobi.mymem.oa;

import org.morfeo.tidmobile.server.oa.BasicApplicationOperation;
import org.morfeo.tidmobile.server.oa.OAException;
import org.morfeo.tidmobile.context.Context;

/* Java code generated by MyMobileWeb Plugin */
public class Cursors_mapper extends BasicApplicationOperation {


@Override
public void execute(Context the_context) throws OAException {


}

}