package mobi.mymem.oa;

import mobi.mymem.MyContextVariables;
import mobi.mymem.MyUtils;
import mobi.mymem.Constants;

import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.URI;
import org.apache.commons.httpclient.methods.GetMethod;
import org.morfeo.tidmobile.server.oa.BasicApplicationOperation;
import org.morfeo.tidmobile.server.oa.OAException;
import org.morfeo.tidmobile.context.Context;

import org.json.JSONArray;
import org.json.JSONObject;

import ezWebAPI.EzWebAPI;

import uk.me.jstott.jcoord.LatLng;
import uk.me.jstott.jcoord.UTMRef;


/* Java code generated by MyMobileWeb Plugin */
public class LocalizeAddress extends BasicApplicationOperation {


@Override
public void execute(Context the_context) throws OAException {
	
	double longitude = 0.0;
	double latitude = 0.0;
	
	double longitudeMark = 0.0;
	double latitudeMark = 0.0;

	if (the_context.isElement(MyContextVariables.LATITUDE) && the_context.isElement(MyContextVariables.LONGITUDE)){
		longitude = (Double)the_context.getElement(MyContextVariables.LONGITUDE);	
		latitude = (Double)the_context.getElement(MyContextVariables.LATITUDE);
	}
	else{
		EzWebAPI API = (EzWebAPI) the_context.getElement(MyContextVariables.EZWEBAPI);
		JSONArray variables = API.getActiveSlots();	
		if (variables != null){
			for (int i=0;i<variables.length();i++){
				try{
					JSONObject variable = variables.getJSONObject(i);
					
					if (variable.getString("name").compareTo("utmCoord")==0){
						//get Latitude and Longitude from UTM
						String[] coords = variable.getString("value").split(","); 
						UTMRef utm = new UTMRef(new Double(coords[0]).doubleValue(), new Double(coords[1]).doubleValue(),'T', 30);
						LatLng latlng = utm.toLatLng();
						latitude = latlng.getLat();
						longitude = latlng.getLng();
						
					}
					else{//Address
						//get the latitude and longitude form the address to allow using the cursors
						GetMethod getLatLong = null;
						try{
							HttpClient geoclient = new HttpClient();
							getLatLong = new GetMethod(new URI(Constants.GEOCODER_URL+"?q="+variable.getString("value")+"&key="+MyUtils.Googlekey, false).getEscapedURI());
							int status = geoclient.executeMethod(getLatLong);
							JSONObject geoData = new JSONObject(getLatLong.getResponseBodyAsString());
							JSONArray coordinates = ((JSONObject) geoData.getJSONArray("Placemark").get(0)).getJSONObject("Point").getJSONArray("coordinates");
							latitude = coordinates.getDouble(1);
							longitude = coordinates.getDouble(0);
						}catch(Exception e){
							//HttpClient not found or server unreachable
							e.printStackTrace();
							latitude = 40.45;
							longitude = -3.65;
						}
						finally{
							if (getLatLong!=null)
								getLatLong.releaseConnection();
						}
					}
				}catch(Exception e){
					//getJSONObject Exception
					e.printStackTrace();
				}	
			}			
		}
	}
	latitudeMark = latitude;
	longitudeMark = longitude;
	
	if (the_context.isElement(MyContextVariables.INCREASELATITUDE))	{
		latitude = latitude + (Double)the_context.getElement(MyContextVariables.INCREASELATITUDE);
		the_context.removeElement(MyContextVariables.INCREASELATITUDE);
	}
	
	if (the_context.isElement(MyContextVariables.INCREASELONGITUDE)){
		longitude = longitude + (Double)the_context.getElement(MyContextVariables.INCREASELONGITUDE);

		if (longitude>180)
			longitude = -180;
		
		if (longitude<-180)
			longitude = 180;

		the_context.removeElement(MyContextVariables.INCREASELONGITUDE);
	}
	
	int zoom = MyUtils.NORMALZOOM;
	if (the_context.isElement(MyContextVariables.ZOOM))
		zoom = (Integer)the_context.getElement(MyContextVariables.ZOOM);
	
	if(the_context.isElement(MyContextVariables.LATITUDEMARK))
		latitudeMark = (Double)the_context.getElement(MyContextVariables.LATITUDEMARK);
	
	if(the_context.isElement(MyContextVariables.LONGITUDEMARK))
		longitudeMark = (Double)the_context.getElement(MyContextVariables.LONGITUDEMARK);
	
	the_context.setElement(MyContextVariables.LATITUDE, latitude);
	the_context.setElement(MyContextVariables.LONGITUDE, longitude);
	the_context.setElement(MyContextVariables.LATITUDEMARK, latitudeMark);
	the_context.setElement(MyContextVariables.LONGITUDEMARK, longitudeMark);	
	
	String urlRequest =  MyUtils.UrlLocalize+"?center="+latitude+","+longitude+"&markers="+latitudeMark+","+longitudeMark+",bluem&zoom="+zoom+"&size="+MyUtils.getWIDTHNORMAL(the_context)+"x"+MyUtils.getHEIGHTNORMAL(the_context)+"&format="+MyUtils.getImageFormat(the_context)+"&maptype=mobile&key="+MyUtils.Googlekey;

	the_context.setElement(MyContextVariables.LOCALIZE,urlRequest);
	
}

}