package mobi.mymem.oa;

import mobi.mymem.MyContextVariables;
import mobi.mymem.MyUtils;

import org.morfeo.tidmobile.server.oa.BasicApplicationOperation;
import org.morfeo.tidmobile.server.oa.OAException;
import org.morfeo.tidmobile.context.Context;

/* Java code generated by MyMobileWeb Plugin */
public class ZoomIn extends BasicApplicationOperation {


@Override
public void execute(Context the_context) throws OAException {
	
	
	if (the_context.isElement(MyContextVariables.ZOOM))
	{
		int zoom = (Integer)the_context.getElement(MyContextVariables.ZOOM);
		
		if (zoom < MyUtils.MAXZOOM)
			zoom ++;
		the_context.setElement(MyContextVariables.ZOOM, zoom);
	}
	else
		the_context.setElement(MyContextVariables.ZOOM, (MyUtils.NORMALZOOM+1)); 


}

}