/**
    -                    ***MyMobileWeb***
    - Java Script code generated by MyMobileWeb Generation Proccess
    - Date: Thu May 29 16:41:25 GMT+01:00 2008
**/

function _MYMW_LG_BT_onsubmit_validate() { 

	// Add your custom code

	return true;
}
