#!/bin/bash

###
# Initialize the database
#
getval() {
	while true; do
		echo -n -e "$1"

		if $getval_noecho ; then
			read -s _val
			echo ""
		else
			read _val
		fi
		
		if ! $getval_checkvalue ; then

			if [ -z "$_val" ] ; then
				_val="$2"
			fi

			break;
		fi

		if [ -z $_val ] ; then
			echo "Invalid value, please try again"
		else
			break
		fi

	done
}

ReadYesOrNo () {
	while true; do
		echo -n -e "$1 [y/n]: "
		read _val
		if [ "$_val" != "y" -a "$_val" != "n" ] ; then
			echo "Invalid value, you should type 'y' or 'n'"
		else
			break
		fi
	done
}

DB_DatabaseExists() {
	db="$1"
	query="select count(datname) from pg_database where datname='$db'"
	_val=$(sudo -u postgres psql -c "$query" -t)
}

DB_UserExists() {
	user="$1"
	query="select count(usename) from pg_user where usename='$user'"
	_val=$(sudo -u postgres psql -c "$query" -t)
}

DB_RemoveDatabase() {
	sudo -u postgres dropdb $1
}

DB_RemoveUser() {
	sudo -u postgres dropuser $1
}

while true; do
	getval_checkvalue=false
	getval_noecho=false

	while true; do
		getval "Select a database name [ezweb]: " "ezweb"
		dbname="$_val"

		DB_DatabaseExists "$dbname"

		if [ $_val = "1" ] ; then
			ReadYesOrNo "Database '$dbname' already exists, remove and create again?"
			if [ $_val = "y" ] ; then
				DB_RemoveDatabase "$dbname"
				break
			else
				echo "Ok, try a different database name"
			fi
		else
			break
		fi
	done
	

	while true; do
		getval "Select a database username [ezweb]: " "ezweb"
		dbuser="$_val"

		DB_UserExists "$dbuser"
		if [ $_val = "1" ] ; then
			
			ReadYesOrNo "User $dbuser already exists, remove and create again?"

			if [ $_val = "y" ] ; then
				if DB_RemoveUser "$dbuser" ; then
					break
				else
					echo "Cannot remove this database user, choose a different one"
				fi
			else
				echo "Ok, try a different username"
			fi
		else
			break
		fi
		
	done

	while true; do
		getval_noecho=true
		getval_checkvalue=true
		getval "Select a database user password: "
		dbpasswd1="$_val"
		
		getval "Please, retype user password: "
		dbpasswd2="$_val"

		if [ "$dbpasswd1" != "$dbpasswd2" ] ; then
			echo "Passwords does not match, try again"
		else
			break
		fi
	done

	getval_checkvalue=false
	getval_noecho=false

	getval "Insert your database host (empty for default): " "127.0.0.1"
	dbhost="$_val"

	getval "Insert your database port (empty for default): "
	dbport="$_val"

	break	
	
done

query="create user $dbuser password '$dbpasswd1'"

sudo -u postgres psql -c "$query" postgres
sudo -u postgres createdb --owner $dbuser $dbname

TMP_PRE="/tmp/ezweb-platform-"
cp /usr/share/ezweb-platform/settings.py ${TMP_PRE}00

cat ${TMP_PRE}00 | sed s/DATABASE_ENGINE.*/"DATABASE_ENGINE = \"postgresql_psycopg2\""/g > ${TMP_PRE}01
cat ${TMP_PRE}01 | sed s/DATABASE_NAME.*/"DATABASE_NAME = \"$dbname\""/g > ${TMP_PRE}02
cat ${TMP_PRE}02 | sed s/DATABASE_USER.*/"DATABASE_USER = \"$dbuser\""/g > ${TMP_PRE}03
cat ${TMP_PRE}03 | sed s/DATABASE_PASSWORD.*/"DATABASE_PASSWORD = \"$dbpasswd1\""/g > ${TMP_PRE}04
cat ${TMP_PRE}04 | sed s/DATABASE_HOST.*/"DATABASE_HOST = \"$dbhost\""/g > ${TMP_PRE}05
cat ${TMP_PRE}05 | sed s/DATABASE_PORT.*/"DATABASE_PORT = \"$dbport\""/g > ${TMP_PRE}06

cp ${TMP_PRE}05 /usr/share/ezweb-platform/settings.py

rm ${TMP_PRE}*

cd /usr/share/ezweb-platform
python manage.py syncdb


