package mobi.mymem;


/* Java code generated by MyMobileWeb Plugin */
public class MyOAs {

public static final String UPLOCALIZE = "UpLocalize";


public static final String CENTER = "Center";

public static final String RIGTHLOCALIZE = "RigthLocalize";


public static final String DOWNLOCALIZE = "DownLocalize";


public static final String ZOOMIN = "ZoomIn";


public static final String LOCALIZEADDRESS = "LocalizeAddress";


public static final String LEFTLOCALIZE = "LeftLocalize";


public static final String ZOOMOUT = "ZoomOut";

public static final String CURSORS_CURSORS_OA = "Cursors_cursors_OA";

public static final String AUTHENTICATE = "Authenticate";


}