package mobi.mymem;


/* Java code generated by MyMobileWeb Plugin */
public class MyPresentations {



public static final String CONTACTS_LOCALIZE = "localize";


public static final String MESSAGES_ERROR = "error";


public static final String MESSAGES_INFORMATION = "information";


public static final String MESSAGES_WARNING = "warning";


public static final String MESSAGES_PLAIN = "plain";


public static final String MESSAGES_QUESTION = "question";


}