#!/bin/bash

###
# Update settings.py
#
TMP_PRE="/tmp/ezweb-platform-"
cp /usr/share/ezweb-platform/settings.py ${TMP_PRE}00


cat ${TMP_PRE}00 | sed s/DATABASE_ENGINE.*/"DATABASE_ENGINE = \"sqlite3\""/g > ${TMP_PRE}01
cat ${TMP_PRE}01 | sed s/DATABASE_NAME.*/"DATABASE_NAME = \"\/var\/lib\/ezweb-platform\/db\""/g > ${TMP_PRE}02

cp ${TMP_PRE}02 /usr/share/ezweb-platform/settings.py

rm ${TMP_PRE}*


###
# Initialize the database
#
mkdir -p /var/lib/ezweb-platform

cd /usr/share/ezweb-platform
python manage.py syncdb

chown -R www-data:www-data /var/lib/ezweb-platform

