<?xml version="1.0" encoding="ISO-8859-1"?>
<%--************************************************** 
 -             ***MyMobileWeb***
 - JSP code generated by MyMobileWeb Generation Proccess 
 - Date: Fri May 30 10:42:58 GMT+01:00 2008
**************************************************--%><%@ page session="true" %><%@ page import="org.morfeo.tidmobile.tags.writers.common.WriterData" %><%@ page import="org.morfeo.tidmobile.cfg.*" %><%@ page import="org.morfeo.tidmobile.server.lc.*" %><%@ page import="org.morfeo.tidmobile.server.*" %><%@ page import="org.morfeo.tidmobile.server.util.*" %><%@ page import="org.morfeo.tidmobile.tags.*" %><%@ page import="org.morfeo.tidmobile.CmtConstants" %><% WriterData wd = new WriterData( out, request, CmtConstants.WML_1_X ); %>
<%
boolean jstl = false;
%>
<%--**************************************************--%>

<%--********CACHE ACTIVATION/DEACTIVATION********--%>
<% {
boolean cache = false;

if( !cache ) CacheConfigurator.resourceExpiresNow( response, wd.getDevice() );
} %>
<%--**************************************************--%>

<%--*************GENERATED CODE BLOCK*****************--%> 
<%!  private int[] lock = new int[0]; %>
<%

{
int wmode = ConfigUtil.getWorkingMode(Configurator.getInstance().getGlobalConfiguration());
DocumentTag documentTag = DocumentCache.getInstance().get( wd.getContext() );
if( jstl || documentTag == null || wmode == ServerConstants.WMODE_DEV ) {
synchronized(lock) {
documentTag = DocumentCache.getInstance().get(wd.getContext());
if(documentTag == null || wmode == ServerConstants.WMODE_DEV) {
documentTag = new DocumentTag();
documentTag.setOpName("Login");   
documentTag.setFamilyName("PdaDevice");  
documentTag.setPresentationName("login");  
documentTag.setId("login");
documentTag.setStyleValues(new String[][]{{"padding","1"},{"margin","1"}});
	{
	HeadTag headTag = null;
	headTag = new HeadTag();
		{
		TitleTag titleTag = null;
		titleTag = new TitleTag();
		titleTag.setStyle("noinclude");
		titleTag.setStyleValues(new String[][]{{"show-separator","true"},{"font-size","-1"},{"font-weight","bold"},{"img-display","both"},{"align","center"},{"include","true"},{"img-position","left"}});
		titleTag.setText("Log in", false, true );
		headTag.addDescendantTag( titleTag );
		}
	documentTag.addDescendantTag( headTag );
	}
	{
	org.morfeo.tidmobile.tags.BodyTag bodyTag = null;
	bodyTag = new org.morfeo.tidmobile.tags.BodyTag();
	bodyTag.setNewcontext("true");
	bodyTag.setStyleValues(new String[][]{{"color","rgb(148, 105, 16)"},{"display-panels-as","plain-flow"},{"background-color","black"},{"panel-links-layout","horizontal"}});
		{
		PTag pTag = null;
		pTag = new PTag("p1");
		pTag.setStyleValues(new String[][]{{"layout","horizontal"},{"align","left"}});
		
                if ("none".equals(pTag.getStyleValue("display"))){                    
                pTag.setDisplay("false");                    
                }
                
		if (TidMobileTag.isDefined(pTag.getStyleValue("paginate"))){
                pTag.setPaginate(pTag.getStyleValue("paginate"));
                }
		pTag.setStyleValue("align", "left");
		pTag.setStyleValue("layout", "vertical");
		            
            if ("true".equals(pTag.getStyleValue("paginate"))){
                documentTag.addParPaginateReference( pTag );
                bodyTag.setHasForm(true);
            }
        
			{
			ImageTag imageTag = null;
			imageTag = new ImageTag("img1","Logo");
			imageTag.setStyle("logo");
			imageTag.setResourceid("mymem_logo", false );
			imageTag.setStyleValues(new String[][]{{"display-as","clickable-image"},{"padding","0"},{"align","middle"},{"border-width","0"},{"margin","0"},{"aspect-ratio","true"}});
			imageTag.setDisplay("${_MYMW_DEVICE.allCapabilities.gif}");
			pTag.addDescendantTag( imageTag );
			}
			{
			LabelTag labelTag = null;
			labelTag = new LabelTag();
			labelTag.setStyleValues(new String[][]{{"img-display","both"},{"img-position","left"}});
			
                if ("none".equals(labelTag.getStyleValue("display"))){                    
                labelTag.setDisplay("false");                    
                }
                
			labelTag.setText("User:", false, true );
			pTag.addDescendantTag( labelTag );
			}
			{
			EntryfieldTag entryfieldTag = null;
			entryfieldTag = new EntryfieldTag("USER");
			entryfieldTag.setBind("${ _MYMW_LOGIN }");
			documentTag.addEntryfieldReference( entryfieldTag );
			entryfieldTag.setStyleValues(new String[][]{{"expand","false"},{"readonly","false"},{"required-mark-position","left"},{"maxlength","100"},{"display-as","simulated-disabled"},{"type","text"},{"required","false"},{"disabled","false"},{"required-mark","true"},{"required-mark-color","red"}});
			
                if ("none".equals(entryfieldTag.getStyleValue("display"))){                    
                entryfieldTag.setDisplay("false");                    
                }
                
			entryfieldTag.setValue("${ _MYMW_LOGIN }", true, false );
			pTag.addDescendantTag( entryfieldTag );
			}
			{
			LabelTag labelTag = null;
			labelTag = new LabelTag();
			labelTag.setStyleValues(new String[][]{{"img-display","both"},{"img-position","left"}});
			
                if ("none".equals(labelTag.getStyleValue("display"))){                    
                labelTag.setDisplay("false");                    
                }
                
			labelTag.setText("Password:", false, true );
			pTag.addDescendantTag( labelTag );
			}
			{
			EntryfieldTag entryfieldTag = null;
			entryfieldTag = new EntryfieldTag("PASS");
			entryfieldTag.setBind("${ _MYMW_PASS }");
			entryfieldTag.setStyle("password");
			documentTag.addEntryfieldReference( entryfieldTag );
			entryfieldTag.setStyleValues(new String[][]{{"expand","false"},{"readonly","false"},{"required-mark-position","left"},{"maxlength","16"},{"display-as","simulated-disabled"},{"type","password"},{"required","true"},{"disabled","false"},{"size","5"},{"required-mark","true"},{"required-mark-color","red"}});
			
                if ("none".equals(entryfieldTag.getStyleValue("display"))){                    
                entryfieldTag.setDisplay("false");                    
                }
                
			entryfieldTag.setValue("${ _MYMW_PASS }", true, false );
			pTag.addDescendantTag( entryfieldTag );
			}
		bodyTag.addDescendantTag( pTag );
		}
		{
		PTag pTag = null;
		pTag = new PTag("p2");
		pTag.setStyleValues(new String[][]{{"layout","horizontal"},{"align","left"}});
		
                if ("none".equals(pTag.getStyleValue("display"))){                    
                pTag.setDisplay("false");                    
                }
                
		if (TidMobileTag.isDefined(pTag.getStyleValue("paginate"))){
                pTag.setPaginate(pTag.getStyleValue("paginate"));
                }
		pTag.setStyleValue("align", "left");
		            
            if ("true".equals(pTag.getStyleValue("paginate"))){
                documentTag.addParPaginateReference( pTag );
                bodyTag.setHasForm(true);
            }
        
			{
			SubmitTag submitTag = null;
			submitTag = new SubmitTag("_MYMW_LG_BT");
			submitTag.setPrincipal("true");
			documentTag.addSubmitReference( submitTag );
			bodyTag.setHasForm(true);
			submitTag.setValue("Enter", false, true );
			submitTag.setStyleValues(new String[][]{{"validate","true"},{"img-position","left"}});
			
                if ("none".equals(submitTag.getStyleValue("display"))){                    
                submitTag.setDisplay("false");                    
                }
                
			pTag.addDescendantTag( submitTag );
			}
		bodyTag.addDescendantTag( pTag );
		}
		{
		PTag pTag = null;
		pTag = new PTag("p5");
		pTag.setStyleValues(new String[][]{{"layout","horizontal"},{"align","left"}});
		
                if ("none".equals(pTag.getStyleValue("display"))){                    
                pTag.setDisplay("false");                    
                }
                
		if (TidMobileTag.isDefined(pTag.getStyleValue("paginate"))){
                pTag.setPaginate(pTag.getStyleValue("paginate"));
                }
		            
            if ("true".equals(pTag.getStyleValue("paginate"))){
                documentTag.addParPaginateReference( pTag );
                bodyTag.setHasForm(true);
            }
        
			{
			LinkTag linkTag = null;
			linkTag = new LinkTag("register");
			linkTag.setResourceid("register");
			linkTag.setStyleValues(new String[][]{{"img-display","both"},{"img-position","left"},{"text-decoration","none"}});
			
                if ("none".equals(linkTag.getStyleValue("display"))){                    
                linkTag.setDisplay("false");                    
                }
                
			linkTag.setText("Register", false, true );
			{
			ImageTag imageTag = new ImageTag();
			linkTag.setStylesImage( imageTag.getStyleValues() );
			}
			pTag.addDescendantTag( linkTag );
			}
		bodyTag.addDescendantTag( pTag );
		}
		{
		BrTag brTag = null;
		brTag = new BrTag();
		brTag.setDisplay("${_MYMW_DEV_BELONGS.PdaDevice}");
		bodyTag.addDescendantTag( brTag );
		}
		{
		PTag pTag = null;
		pTag = new PTag("p6");
		pTag.setStyle("menu");
		pTag.setStyleValues(new String[][]{{"layout","horizontal"},{"align","left"}});
		
                if ("none".equals(pTag.getStyleValue("display"))){                    
                pTag.setDisplay("false");                    
                }
                
		if (TidMobileTag.isDefined(pTag.getStyleValue("paginate"))){
                pTag.setPaginate(pTag.getStyleValue("paginate"));
                }
		            
            if ("true".equals(pTag.getStyleValue("paginate"))){
                documentTag.addParPaginateReference( pTag );
                bodyTag.setHasForm(true);
            }
        
			{
			LinkTag linkTag = null;
			linkTag = new LinkTag("lnk_1");
			linkTag.setResourceid("spain");
			linkTag.setStyle("menu");
			linkTag.setStyleValues(new String[][]{{"img-display","both"},{"img-position","left"},{"text-decoration","none"}});
			
                if ("none".equals(linkTag.getStyleValue("display"))){                    
                linkTag.setDisplay("false");                    
                }
                
			linkTag.setText("Español", false, true );
			linkTag.setHref("DH?_MYMW_LANG=es_ES", false, false );
			{
			ImageTag imageTag = new ImageTag();
			linkTag.setStylesImage( imageTag.getStyleValues() );
			}
			pTag.addDescendantTag( linkTag );
			}
			{
			LinkTag linkTag = null;
			linkTag = new LinkTag("lnk_2");
			linkTag.setResourceid("england");
			linkTag.setStyle("menu");
			linkTag.setStyleValues(new String[][]{{"img-display","both"},{"img-position","left"},{"text-decoration","none"}});
			
                if ("none".equals(linkTag.getStyleValue("display"))){                    
                linkTag.setDisplay("false");                    
                }
                
			linkTag.setText("English", false, true );
			linkTag.setHref("DH?_MYMW_LANG=en_US", false, false );
			{
			ImageTag imageTag = new ImageTag();
			linkTag.setStylesImage( imageTag.getStyleValues() );
			}
			pTag.addDescendantTag( linkTag );
			}
		bodyTag.addDescendantTag( pTag );
		}
	documentTag.addDescendantTag( bodyTag );
	}
DocumentCache.getInstance().put(wd.getContext(),documentTag);
}
}
}

documentTag.write_wml_1(wd);
}%>