#!/bin/bash

###
# Remove .pyc files
#
rm -f $(find /usr/share/ezweb-platform -name "*.pyc")

###
# Unlink virtual host link
#
vh_link="/etc/apache2/sites-enabled/010-ezweb-platform"
if [ -e $vh_link ] ; then
	unlink $vh_link
fi

###
# Unlink settings.py from /etc
#
settings_link="/etc/ezweb-platform/settings.py"
if [ -e $settings_link ] ; then
	unlink $settings_link
fi

