#!/bin/sh

###
# Include debconf module
#
. /usr/share/debconf/confmodule

###
# Set the correct file owner
#
chown -R root:root /usr/share/ezweb-platform
chown root:root /etc/apache2/sites-available/ezweb-platform

###
# Create a link to settings in /etc
#
ln -s /usr/share/ezweb-platform/settings.py /etc/ezweb-platform/settings.py



###
# Read ezweb hostname from user
#
db_input high ezweb/hostname
db_go

db_get ezweb/hostname
hostname=$RET

###
# Update apache conf files
#
cat /etc/apache2/sites-available/ezweb-platform | sed s/localhost/$hostname/g > /tmp/ezweb-postinst
mv /tmp/ezweb-postinst /etc/apache2/sites-available/ezweb-platform

vh_file="/etc/apache2/sites-available/ezweb-platform"
vh_link="/etc/apache2/sites-enabled/010-ezweb-platform"

if [ ! -e $vh_link ]; then
	ln -s $vh_file $vh_link
fi

### 
# Create the Apache 2 files layout
#
mkdir -p /var/www/ezweb-platform/gadgets
chown -R www-data:www-data /var/www/ezweb-platform


###
# Restart apache 2 web server
###
if [ -e /var/run/apache2.pid ]; then
	db_input low ezweb/apache2/reload
	db_go
	db_get ezweb/apache2/reload

	if [ "true" = $RET ]; then
		/etc/init.d/apache2 reload
	fi
else
  db_input low ezweb/apache2/start
  db_go
  db_get ezweb/apache2/start
  
  if [ "true" = $RET ]; then
    /etc/init.d/apache2 start
  fi

fi

db_stop

