import sys
import os
import shutil

import string
from random import Random

import gettext
from gettext import gettext as _

import psycopg2
from admintools.common import Command, EzWebAdminToolResources
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
from optparse import OptionParser, make_option
from configobj import ConfigObj


class PostgreSQLResources:

  def __init__(self, resources):
    self.resources = resources

  def get_ezweb_connection(self, cfg):
    conn = psycopg2.connect (host = cfg["host"],
                             user = cfg["admin_user"],
                             password = cfg['admin_pass'])
    conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    return conn

  def connect(self, cfg):
    conn = psycopg2.connect (host     = cfg['host'],
                             user     = cfg['user'],
                             password = cfg['pass'],
                             database = cfg['name'])
    return conn

  def get_postgres_settings_path(self):
    return self.resources.CONFIG_BASE_PATH + "postgres.conf"

  def get_postgres_settings(self):
    filename = self.get_postgres_settings_path()

    exists = os.path.exists(filename)
    if exists:
      cfg = ConfigObj(filename, encoding="utf_8")
    else:
      cfg = ConfigObj()
      cfg.filename = filename
      cfg.encoding= "utf_8"

    cfg.initial_comment  = []
    cfg.initial_comment.append("#")
    cfg.initial_comment.append("# DO NOT EDIT THIS FILE")
    cfg.initial_comment.append("#")
    cfg.initial_comment.append("# It is automatically generated by the EzWeb admin tools")
    cfg.initial_comment.append("")

    return cfg

  def save_postgres_settings(self, cfg, backup):
    if backup and os.path.exists(cfg.filename):
      self.resources.printMsg("Backing up \"%s\"... " % cfg.filename)
      shutil.copyfile(cfg.filename, cfg.filename + "~")
      self.resources.printlnMsgNP("Done")

    self.resources.printMsg("Saving EzWeb PostgreSQL settings (%s)... " % cfg.filename)
    cfg.write()
    os.chmod(cfg.filename, 0600)
    self.resources.printlnMsgNP("Done")

  def fill_settings(self, site_cfg):
    conf_name = site_cfg['name']

    if site_cfg['database'].has_key('schema'):
      schema = site_cfg['database']['schema']
    else:
      schema = "default"

    postgres_settings = self.get_postgres_settings()
    if postgres_settings.has_key(schema):
      schema = postgres_settings[schema]
    else:
      schema = {}

    # Database host
    if not site_cfg['database'].has_key("host"):
      if schema.has_key('server_host'):
        site_cfg['database']['host'] = schema['server_host']
      else:
        site_cfg['database']['host'] = "localhost"

    # Database admin user
    if not site_cfg['database'].has_key("admin_user"):
      if schema.has_key('admin_user'):
        site_cfg['database']['admin_user'] = schema['admin_user']

    if not site_cfg['database'].has_key("admin_pass"):
      if schema.has_key('admin_pass'):
        site_cfg['database']['admin_pass'] = schema['admin_pass']

    # Database user
    if not site_cfg['database'].has_key("user"):
      site_cfg['database']['user'] = "ezweb-" + conf_name

    if not site_cfg['database'].has_key("name"):
      site_cfg['database']['name'] = "ezweb-" + conf_name

    if not site_cfg['database'].has_key("pass"):
      site_cfg['database']['pass'] = ''.join(Random().sample(string.letters+string.digits, 12))

    return site_cfg

  def update_settings_py(self, template, site_cfg):

    # Fill the template
    template.replace("DATABASE_ENGINE", "postgresql_psycopg2")
    template.replace("DATABASE_USER", site_cfg['database']['user'])
    if site_cfg['database'].has_key('pass'):
      template.replace("DATABASE_PASS", site_cfg['database']['pass'])
    else:
      template.replace("DATABASE_PASS", "")

    template.replace("DATABASE_NAME", site_cfg['database']['name'])
    template.replace("DATABASE_OPTIONS", "")

    if site_cfg['database'].has_key('host'):
      template.replace("DATABASE_HOST", site_cfg['database']['host'])
    else:
      template.replace("DATABASE_HOST", "")

    if site_cfg['database'].has_key('port'):
      template.replace("DATABASE_PORT", site_cfg['database']['port'])
    else:
      template.replace("DATABASE_PORT", "")

  def drop_db_if_exists(self, cursor, settings):
    cursor.execute("SELECT 1 FROM pg_database WHERE datname='" + settings['name'] + "';")
    if cursor.rowcount == 1:
      self.resources.printMsg("Droping database \"%s\"... " % settings['name'])
      cursor.execute("DROP DATABASE \"" + settings['name'] + "\";")
      self.resources.printlnMsgNP("Done")

  def drop_user_if_exists(self, cursor, settings):
    cursor.execute("SELECT 1 FROM pg_user WHERE usename = '" + settings['user'] + "';")
    if cursor.rowcount == 1:
      self.resources.printMsg("Droping user \"%s\"... " % settings['user'])
      cursor.execute("DROP ROLE \"" + settings['user'] + "\";")
      self.resources.printlnMsgNP("Done")

  def create_db(self, cursor, settings):
    cursor.execute("CREATE DATABASE \"" + settings['name'] + "\" OWNER \"" + settings['user'] + "\";")


class UpdateCommand(Command):
  option_list = [make_option("--database-user","--database-user", action="store",
                             dest="database_user", help=_("Try to run a dist-upgrade")),
                 make_option("--database-name","--database-name", action="store",
                             dest="database_name", help=_("Try to run a dist-upgrade")),
                 make_option("--database-pass","--database-pass", action="store",
                             dest="database_pass", help=_("Try to run a dist-upgrade")),
                 make_option("--database-host","--database-host", action="store",
                             dest="database_host", help=_("Try to run a dist-upgrade"))
                ]

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, options, site_cfg):
    if options.database_host != None:
      site_cfg['database']['host'] = options.database_host

    if options.database_user != None:
      site_cfg['database']['user'] = options.database_user

    if options.database_name != None:
      site_cfg['database']['name'] = options.database_name

    if options.database_pass != None:
      site_cfg['database']['pass'] = options.database_pass

class ProcessCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)
    self.resources = resources

  def execute(self, options, site_cfg, settings_template):
    self.psqlResources.fill_settings(site_cfg)

    cfg = site_cfg['database']

    self.psqlResources.update_settings_py(settings_template, site_cfg)

    conn = self.psqlResources.get_ezweb_connection(cfg)
    cursor = conn.cursor()

    cursor.execute("SELECT 1 FROM pg_user WHERE usename = '" + cfg['user'] + "';")
    if cursor.rowcount == 0:
      self.resources.printMsg("User " + cfg['user'] + " doesn't exists... ")
      cursor.execute("CREATE USER \"" + cfg['user'] + "\" PASSWORD '" + cfg['pass'] + "';")
      self.resources.printlnMsgNP("created")


    cursor.execute("SELECT 1 FROM pg_database WHERE datname='" + cfg['name'] + "';")
    if cursor.rowcount == 0:
      self.resources.printMsg("Database %s doesn't exists... " % cfg['name'])
      self.psqlResources.create_db(cursor, cfg)
      self.resources.printlnMsgNP("created");

class PurgeCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, site_cfg, options):
    self.psqlResources.fill_settings(site_cfg);
    cfg = site_cfg['database']

    conn = self.psqlResources.get_ezweb_connection(cfg)
    cursor = conn.cursor()
    self.psqlResources.drop_db_if_exists(cursor, cfg)
    self.psqlResources.drop_user_if_exists(cursor, cfg)

class ClearCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, site_cfg, options):
    self.psqlResources.fill_settings(site_cfg);
    cfg = site_cfg['database']

    conn = self.psqlResources.get_ezweb_connection(cfg)
    cursor = conn.cursor()
    self.psqlResources.drop_db_if_exists(cursor, cfg)
    self.psqlResources.create_db(cursor, cfg)

class GetDefaultsCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, schema_name, options):
    schema_settings = self.psqlResources.get_postgres_settings()

    if schema_settings.has_key(schema_name):
      cfg = schema_settings[schema_name]
    else:
      cfg = {}

    if cfg.has_key("server_host"):
      print "SERVER_HOST=" + cfg["server_host"]
    else:
      print "SERVER_HOST="

    if cfg.has_key("admin_user"):
      print "ADMIN_USER=" + cfg["admin_user"]
    else:
      print "ADMIN_USER="

    if cfg.has_key("admin_pass"):
      print "ADMIN_PASS=" + cfg["admin_pass"]
    else:
      print "ADMIN_PASS="


class SetDefaultsCommand(Command):
  option_list = [make_option("--database-host","--database-host", action="store",
                             dest="database_host", help=_("Address of the server where the database is hosted")),
                 make_option("--admin-user","--admin-user", action="store",
                             dest="admin_user", help=_("User to use for administre PostgeSQL databases")),
                 make_option("--admin-pass","--admin-pass", action="store",
                             dest="admin_pass", help=_("Password associated to the admin user")),
                ]

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, schema_name, options):
    schema_settings = self.psqlResources.get_postgres_settings()

    if schema_settings.has_key(schema_name):
      cfg = schema_settings[schema_name]
    else:
      schema_settings[schema_name] = {}
      cfg = schema_settings[schema_name]

    if options.database_host != None:
      cfg["server_host"] = options.database_host

    if options.admin_user != None:
      cfg["admin_user"] = options.admin_user

    if options.admin_pass != None:
      cfg["admin_pass"] = options.admin_pass

    self.psqlResources.save_postgres_settings(schema_settings, options.backup)

