# -*- coding: utf-8 -*-

#...............................licence...........................................
#
#     (C) Copyright 2008 Telefonica Investigacion y Desarrollo
#     S.A.Unipersonal (Telefonica I+D)
#
#     This file is part of Morfeo EzWeb Platform.
#
#     Morfeo EzWeb Platform is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Morfeo EzWeb Platform is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with Morfeo EzWeb Platform.  If not, see <http://www.gnu.org/licenses/>.
#
#     Info about members and contributors of the MORFEO project
#     is available at
#
#     http://morfeo-project.org
#
#...............................licence...........................................#


#

import sys
import os
import shutil

import string
from random import Random

import gettext
from gettext import gettext as _

import psycopg2
from admintools.common import Command, EzWebAdminToolResources, ConfigCopy, AuthException
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
from optparse import OptionParser, make_option
from configobj import ConfigObj


class PostgreSQLResources:

  def __init__(self, resources):
    self.resources = resources

  def get_ezweb_connection(self, cfg):
    conn = psycopg2.connect (host = cfg.getDefault('localhost', 'database', "host"),
                             user = cfg.getDefault('', 'database', "admin_user"),
                             password = cfg.getDefault('', 'database', 'admin_pass'))
    conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    return conn

  def connect(self, cfg):
    conn = psycopg2.connect (host     = cfg.get('database', 'host'),
                             user     = cfg.get('database', 'user'),
                             password = cfg.get('database', 'pass'),
                             database = cfg.get('database', 'name'))
    return conn

  def get_postgres_settings_path(self):
    return self.resources.CONFIG_BASE_PATH + "postgres.conf"

  def get_postgres_settings(self):
    filename = self.get_postgres_settings_path()

    exists = os.path.exists(filename)
    if exists:
      cfg = ConfigObj(filename, encoding="utf_8")
    else:
      cfg = ConfigObj()
      cfg.filename = filename
      cfg.encoding= "utf_8"

    cfg.initial_comment  = []
    cfg.initial_comment.append("#")
    cfg.initial_comment.append("# DO NOT EDIT THIS FILE")
    cfg.initial_comment.append("#")
    cfg.initial_comment.append("# It is automatically generated by the EzWeb admin tools")
    cfg.initial_comment.append("")

    return cfg

  def save_postgres_settings(self, cfg, backup):
    if backup and os.path.exists(cfg.filename):
      self.resources.printMsg("Backing up \"%s\"... " % cfg.filename)
      shutil.copyfile(cfg.filename, cfg.filename + "~")
      self.resources.printlnMsgNP("Done")

    self.resources.printMsg("Saving EzWeb PostgreSQL settings (%s)... " % cfg.filename)
    cfg.write()
    os.chmod(cfg.filename, 0600)
    self.resources.printlnMsgNP("Done")

  def update_settings_py(self, template, site_cfg):

    # Fill the template
    template.replace("DATABASE_ENGINE", "postgresql_psycopg2")
    template.replace("DATABASE_USER", site_cfg.get('database', 'user'))
    template.replace("DATABASE_PASS", site_cfg.get('database', 'pass'))

    template.replace("DATABASE_NAME", site_cfg.get('database', 'name'))
    template.replace("DATABASE_OPTIONS", "")

    template.replace("DATABASE_HOST", site_cfg.getDefault('', 'database', 'host'))
    template.replace("DATABASE_PORT", site_cfg.getDefault('', 'database', 'port'))

  def drop_db_if_exists(self, cursor, settings):
    databaseName = settings.get('database', 'name')
    cursor.execute("SELECT 1 FROM pg_database WHERE datname='" + databaseName + "';")
    if cursor.rowcount == 1:
      self.resources.printMsg("Droping database \"%s\"... " % databaseName)
      cursor.execute("DROP DATABASE \"" + databaseName + "\";")
      self.resources.printlnMsgNP("Done")

  def drop_user_if_exists(self, cursor, settings):
    user = settings.get('database', 'user')
    cursor.execute("SELECT 1 FROM pg_user WHERE usename = '" + user + "';")
    if cursor.rowcount == 1:
      self.resources.printMsg("Droping user \"%s\"... " % user)
      cursor.execute("DROP USER \"" + user + "\";")
      self.resources.printlnMsgNP("Done")

  def create_db(self, cursor, settings):
    cursor.execute("CREATE DATABASE \"" + settings.get('database', 'name') + "\" OWNER \"" + settings.get('database', 'user') + "\";")


class FillConfigCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)
    self.resources = resources

  def execute(self, site_cfg):

    conf_name = site_cfg["name"]

    schema = site_cfg.getDefault('', 'database', 'schema')
    if schema == '':
      site_cfg.set("default", 'database', 'schema')
      schema = "default"

    postgres_settings = self.psqlResources.get_postgres_settings()
    if postgres_settings.has_key(schema):
      schema = postgres_settings[schema]
    else:
      schema = {}

    # Database host
    host = site_cfg.getDefault('', 'database', 'host')
    if host == '':
      if schema.has_key('server_host'):
        site_cfg.set(schema['server_host'], 'database', 'host')
      else:
        site_cfg.set("localhost", 'database', 'host')

    # Database admin user
    admin_user = site_cfg.getDefault('', 'database', 'admin_user')
    if admin_user == '':
      if schema.has_key('admin_user'):
        site_cfg.set(schema['admin_user'], 'database', 'admin_user')

    admin_pass = site_cfg.getDefault('', 'database', 'admin_pass')
    if admin_pass == '':
      if schema.has_key('admin_pass'):
        site_cfg.set(schema['admin_pass'], 'database', 'admin_pass')

    # Database user
    if site_cfg.getDefault('', 'database', 'user') == '':
      site_cfg.setAndUpdate("ezweb-" + conf_name, 'database', 'user')

    # Database name
    if site_cfg.getDefault('', 'database', 'name') == '':
      site_cfg.setAndUpdate("ezweb-" + conf_name, 'database', 'name')

    # Database password
    if site_cfg.getDefault('', 'database', 'pass') == '':
      site_cfg.setAndUpdate(''.join(Random().sample(string.letters+string.digits, 12)), 'database', 'pass')


class UpdateCommand(Command):
  option_list = [make_option("--database-user", action="store",
                             dest="database_user", help=_("User to use to connect to the database")),
                 make_option("--database-name", action="store",
                             dest="database_name", help=_("Name of the database to use")),
                 make_option("--database-pass", action="store",
                             dest="database_pass", help=_("Password to use to connect to the database server")),
                 make_option("--database-host", action="store",
                             dest="database_host", help=_("Address of the database server"))
                ]

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, site_cfg, options):
    if options.database_host != None:
      site_cfg.setAndUpdate(options.database_host, 'database', 'host')

    if options.database_user != None:
      site_cfg.setAndUpdate(options.database_user, 'database', 'user')

    if options.database_name != None:
      site_cfg.setAndUpdate(options.database_name, 'database', 'name')

    if options.database_pass != None:
      site_cfg.setAndUpdate(options.database_pass, 'database', 'pass')

class ProcessCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)
    self.resources = resources

  def execute(self, options, cfg, settings_template):

    try:
      self.psqlResources.update_settings_py(settings_template, cfg)

      conn = self.psqlResources.get_ezweb_connection(cfg)
      cursor = conn.cursor()

      user = cfg.get('database', 'user')
      passwd = cfg.get('database', 'pass')
      databaseName = cfg.get('database', 'name')
      cursor.execute("SELECT 1 FROM pg_user WHERE usename = '" + user + "';")
      if cursor.rowcount == 0:
        self.resources.printMsg("User " + user + " doesn't exists... ")
        cursor.execute("CREATE USER \"" + user + "\" PASSWORD '" + passwd + "';")
        self.resources.printlnMsgNP("created")


      cursor.execute("SELECT 1 FROM pg_database WHERE datname='" + databaseName + "';")
      if cursor.rowcount == 0:
        self.resources.printMsg("Database %s doesn't exists... " % databaseName)
        self.psqlResources.create_db(cursor, cfg)
        self.resources.printlnMsgNP("created");
    except psycopg2.OperationalError, e:
      raise AuthException()

class PurgeCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, cfg, options):
    conn = self.psqlResources.get_ezweb_connection(cfg)
    cursor = conn.cursor()
    self.psqlResources.drop_db_if_exists(cursor, cfg)
    self.psqlResources.drop_user_if_exists(cursor, cfg)

class CleanCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, cfg, options):
    conn = self.psqlResources.get_ezweb_connection(cfg)
    cursor = conn.cursor()
    self.psqlResources.drop_db_if_exists(cursor, cfg)
    self.psqlResources.create_db(cursor, cfg)

class GetDefaultsCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, schema_name, options):
    schema_settings = self.psqlResources.get_postgres_settings()

    if schema_settings.has_key(schema_name):
      cfg = schema_settings[schema_name]
    else:
      cfg = {}

    if cfg.has_key("server_host"):
      print "SERVER_HOST=" + cfg["server_host"]
    else:
      print "SERVER_HOST="

    if cfg.has_key("admin_user"):
      print "ADMIN_USER=" + cfg["admin_user"]
    else:
      print "ADMIN_USER="

    if cfg.has_key("admin_pass"):
      print "ADMIN_PASS=" + cfg["admin_pass"]
    else:
      print "ADMIN_PASS="


class SetDefaultsCommand(Command):
  option_list = [make_option("--database-host", action="store",
                             dest="database_host", help=_("Address of the server where the database is hosted")),
                 make_option("--admin-user", action="store",
                             dest="admin_user", help=_("User to use for managing the PostgeSQL databases")),
                 make_option("--admin-pass", action="store",
                             dest="admin_pass", help=_("Password associated to the admin user")),
                ]

  def __init__(self, resources):
    self.psqlResources = PostgreSQLResources(resources)

  def execute(self, schema_name, options):
    schema_settings = self.psqlResources.get_postgres_settings()

    if schema_settings.has_key(schema_name):
      cfg = schema_settings[schema_name]
    else:
      schema_settings[schema_name] = {}
      cfg = schema_settings[schema_name]

    if options.database_host != None:
      cfg["server_host"] = options.database_host

    if options.admin_user != None:
      cfg["admin_user"] = options.admin_user

    if options.admin_pass != None:
      cfg["admin_pass"] = options.admin_pass

    self.psqlResources.save_postgres_settings(schema_settings, options.backup)

