/**
    -                    ***MyMobileWeb***
    - Java Script code generated by MyMobileWeb Generation Proccess
    - Date: Fri Jun 13 11:27:58 GMT+01:00 2008
    - Note: DO NOT TOUCH
**/

function _smt_npr_onsubmit_gen_validate() { 

	var resul = _MYMW_LG_BT_onsubmit_gen_validate();
	if (resul) { return true; } else { return false; }

}

function _MYMW_LG_BT_onsubmit_gen_validate() { 

 // Validate control: USER_VAL
 if(document.forms[0].USER_VAL) {

	// Validate Required .. 
	var vUSER = trim(document.forms[0].USER_VAL.value);
	if(vUSER == "") {

		var parameters = new Array('Usuario:');
		alert(messageFormat(getMessage('MyMobileWeb_E_Required'),parameters));
		return false;
	}

	// Validate Format .. 
	if ( ( vUSER.length < 0 ) || ( vUSER.length > 16 ) ) {
		var parameters = new Array('Usuario:','0','16');
		alert(messageFormat(getMessage('MyMobileWeb_E_Min_Max_Length'),parameters));
		return false;
	}

 }

 // Validate control: PASS_VAL
 if(document.forms[0].PASS_VAL) {

	// Validate Required .. 
	var vPASS = trim(document.forms[0].PASS_VAL.value);
	if(vPASS == "") {

		var parameters = new Array('Clave:');
		alert(messageFormat(getMessage('MyMobileWeb_E_Required'),parameters));
		return false;
	}

	// Validate Format .. 
	if ( ( vPASS.length < 0 ) || ( vPASS.length > 16 ) ) {
		var parameters = new Array('Clave:','0','16');
		alert(messageFormat(getMessage('MyMobileWeb_E_Min_Max_Length'),parameters));
		return false;
	}

 }

 if(typeof _MYMW_LG_BT_onsubmit_validate == 'function') { var result = _MYMW_LG_BT_onsubmit_validate(); } 


 if ( result ) return true;
 else return false;

}
