# -*- coding: utf-8 -*-

#...............................licence...........................................
#
#     (C) Copyright 2008 Telefonica Investigacion y Desarrollo
#     S.A.Unipersonal (Telefonica I+D)
#
#     This file is part of Morfeo EzWeb Platform.
#
#     Morfeo EzWeb Platform is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Morfeo EzWeb Platform is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with Morfeo EzWeb Platform.  If not, see <http://www.gnu.org/licenses/>.
#
#     Info about members and contributors of the MORFEO project
#     is available at
#
#     http://morfeo-project.org
#
#...............................licence...........................................#


#
import os
import shutil

import gettext
from gettext import gettext as _

from configobj import ConfigObj
from admintools.common import Command, AuthMethod
from optparse import make_option

class EzSteroidsResources:
  def __init__(self, resources):
    self.resources = resources

  def get_ezsteroids_settings_path(self):
    return self.resources.CONFIG_BASE_PATH + "ezsteroids.conf"

  def get_ezsteroids_settings(self):
    filename = self.get_ezsteroids_settings_path()

    exists = os.path.exists(filename)
    if exists:
      cfg = ConfigObj(filename, encoding="utf_8")
    else:
      cfg = ConfigObj()
      cfg.filename = filename
      cfg.encoding= "utf_8"

    cfg.initial_comment  = []
    cfg.initial_comment.append("#")
    cfg.initial_comment.append("# DO NOT EDIT THIS FILE")
    cfg.initial_comment.append("#")
    cfg.initial_comment.append("# It is automatically generated by the EzWeb admin tools")
    cfg.initial_comment.append("")

    return cfg

  def save_ezsteroids_settings(self, cfg, backup):
    if backup and os.path.exists(cfg.filename):
      self.resources.printMsg("Backing up \"%s\"... " % cfg.filename)
      shutil.copyfile(cfg.filename, cfg.filename + "~")
      self.resources.printlnMsgNP("Done")

    self.resources.printMsg("Saving EzWeb EzSteroids settings (%s)... " % cfg.filename)
    cfg.write()
    os.chmod(cfg.filename, 0600)
    self.resources.printlnMsgNP("Done")


class AuthMethod(AuthMethod):

  def __init__(self, resources):
    self.ezsteroidsResources = EzSteroidsResources(resources)
    self.resources = resources

  def getMiddlewareClasses(self):
    return []

  def getBackends(self):
    return ['authentication.ezsteroidsaccess.EzSteroidsBackend']

  def processConf(self, site_cfg):

    if not site_cfg.has_key("ezsteroids"):
      site_cfg["ezsteroids"] = {}

    ezsteroids_cfg = site_cfg["ezsteroids"]

    if ezsteroids_cfg.has_key("schema"):
      schema_name = ezsteroids_cfg["schema"]
    else:
      schema_name = "default"

    schema = self.ezsteroidsResources.get_ezsteroids_settings()

    if schema.has_key(schema_name):
      schema = schema[schema_name]
    else:
      schema = {}

    # EzSteroids url
    if ezsteroids_cfg.has_key("server"):
      ezsteroids_url = ezsteroids_cfg["server"]
    elif schema.has_key("server"):
      ezsteroids_url = schema["server"]
    else:
      ezsteroids_url = ""

    conf  = "# EzSteroids Auth Backend conf\n"
    conf += "AUTHENTICATION_SERVER_URL = '%s'\n" % ezsteroids_url
    return conf


class UpdateCommand(Command):

  option_list = [make_option("--ezsteroids-server", action="store",
                             dest="ezsteroids_server", help=_("EzSteroids server to use")),
                ]

  def __init__(self, resources):
    self.resources = resources

  def execute(self, site_cfg, options):

    if not site_cfg.has_key("ezsteroids"):
      site_cfg["ezsteroids"] = {}

    ezsteroids_cfg = site_cfg["ezsteroids"]

    if options.ezsteroids_server != None:
      ezsteroids_cfg['server'] = options.ezsteroids_server


class GetDefaultsCommand(Command):
  option_list = []

  def __init__(self, resources):
    self.ezsteroidsResources = EzSteroidsResources(resources)

  def execute(self, schema_name, options):
    schema_settings = self.ezsteroidsResources.get_ezsteroids_settings()

    if schema_settings.has_key(schema_name):
      cfg = schema_settings[schema_name]
    else:
      cfg = {}

    if cfg.has_key("server"):
      print "SERVER_URL=" + cfg["server"]
    else:
      print "SERVER_URL="


class SetDefaultsCommand(Command):
  option_list = [make_option("--ezsteroids-server", action="store",
                             dest="ezsteroids_server", help=_("EzSteroids server to use")),
                ]

  def __init__(self, resources):
    self.ezsteroidsResources = EzSteroidsResources(resources)

  def execute(self, schema_name, options):
    schema_settings = self.ezsteroidsResources.get_ezsteroids_settings()

    if schema_settings.has_key(schema_name):
      cfg = schema_settings[schema_name]
    else:
      schema_settings[schema_name] = {}
      cfg = schema_settings[schema_name]

    if options.ezsteroids_server != None:
      cfg["server"] = options.ezsteroids_server

    self.ezsteroidsResources.save_ezsteroids_settings(schema_settings, options.backup)
