#!/bin/bash

set -e

###
# Include debconf module
#
. /usr/share/debconf/confmodule

if [ "$1" = "configure" -o "$2" = "reconfigure" ]; then
  EZWEB_ADMIN_SCRIPT="update-ezweb-platform"

  db_get ezweb-platform-lighttpd-common/defaultservername
  SERVER_NAME="$RET"

  db_get ezweb-platform-lighttpd-common/defaultserverport
  SERVER_PORT="$RET"

  $EZWEB_ADMIN_SCRIPT setserverdefaults lighttpd default --server-name "$SERVER_NAME" --server-port "$SERVER_PORT"
fi

#DEBHELPER#

exit 0
