#!/bin/bash

###
# Include debconf module
#
. /usr/share/debconf/confmodule

if [ "$1" = "configure" -o "$1" = "reconfigure" ]; then
  EZWEB_ADMIN_SCRIPT="/usr/sbin/update-ezweb-platform"

  db_get ezweb-platform-apache2-common/defaultservername
  SERVER_NAME="$RET"

  db_get ezweb-platform-apache2-common/defaultserverport
  SERVER_PORT="$RET"

  $EZWEB_ADMIN_SCRIPT setserverdefaults apache2 default --server-name "$SERVER_NAME" --server-port "$SERVER_PORT"
fi

#DEBHELPER#

exit 0
