#!/bin/bash

set -e

###
# Include debconf module
#
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then

  EZWEB_ADMIN_SCRIPT="update-ezweb-platform"

  db_get ezweb-platform-ldap/serveraddress
  SERVER_HOST="$RET"

  db_get ezweb-platform-ldap/search-dn
  SEARCH_DN="$RET"

  $EZWEB_ADMIN_SCRIPT setauthdefaults ldap default --ldap-server "$SERVER_HOST" --ldap-search-dn "$SEARCH_DN"
fi

#DEBHELPER#

db_stop
exit 0
