#!/bin/bash

set -e

###
# Include debconf module
#
. /usr/share/debconf/confmodule

if [ "$1" = "configure" -o "$1" = "reconfigure" ]; then

  EZWEB_ADMIN_SCRIPT="update-ezweb-platform"

  db_get ezweb-platform-ezsteroids/serveraddress
  SERVER_HOST="$RET"

  $EZWEB_ADMIN_SCRIPT setauthdefaults ezsteroids default --ezsteroids-server "$SERVER_HOST"
  #$EZWEB_ADMIN_SCRIPT setdefaults defaults --server-type apache2 --connection-type fastcgi
fi

#DEBHELPER#

db_stop
exit 0
