#!/bin/bash

###
# Include debconf module
#
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
  EZWEB_ADMIN_SCRIPT="/usr/sbin/update-ezweb-platform"

  if [ -f "/etc/ezweb-platform/apache2.conf" ]; then
    # Get previous configuration
    RET=`$EZWEB_ADMIN_SCRIPT getserverdefaults apache2 default`
    eval $RET

    db_set ezweb-platform-apache2-common/defaultservername "$SERVER_NAME"
    db_set ezweb-platform-apache2-common/defaultserverport "$SERVER_PORT"
  else
    # Establish the defaults values
    db_set ezweb-platform-apache2-common/defaultservername `hostname -f`
    db_set ezweb-platform-apache2-common/defaultserverport "8000"
  fi

  ###
  # Read apache2 config from user
  #

  db_input medium ezweb-platform-apache2-common/defaultservername
  db_go

  db_get ezweb-platform-apache2-common/defaultservername
  SERVER_NAME="$RET"

  db_input medium ezweb-platform-apache2-common/defaultserverport
  db_go

  db_get ezweb-platform-apache2-common/defaultserverport
  SERVER_PORT="$RET"

  $EZWEB_ADMIN_SCRIPT setserverdefaults apache2 default --server-name "$SERVER_NAME" --server-port "$SERVER_PORT"

fi

#DEBHELPER#

exit 0
