#!/bin/bash

###
# Include debconf module
#
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
  APACHE2_ADMIN_SCRIPT="/usr/share/ezweb-platform/admintools/server-backends/apache2"

  if [ -f "/etc/ezweb-platform/apache2.conf" ]; then
    # Get previous configuration
    RET=`$APACHE2_ADMIN_SCRIPT getdefaults default`
    eval $RET

    db_set ezweb-platform-apache2-common/defaultservername "$SERVER_NAME"
    db_set ezweb-platform-apache2-common/defaultserverport "$SERVER_PORT"
  else
    # Establish the defaults values
    db_set ezweb-platform-apache2-common/defaultservername `hostname -f`
    db_set ezweb-platform-apache2-common/defaultserverport "80"
  fi

  ###
  # Read apache2 config from user
  #

  db_input low ezweb-platform-apache2-common/defaultservername
  db_go

  db_get ezweb-platform-apache2-common/defaultservername
  SERVER_NAME="$RET"

  db_input low ezweb-platform-apache2-common/defaultserverport
  db_go

  db_get ezweb-platform-apache2-common/defaultserverport
  SERVER_PORT="$RET"

  $APACHE2_ADMIN_SCRIPT setdefaults default --server-name "$SERVER_NAME" --server-port "$SERVER_PORT"

fi

exit 0
