#!/usr/bin/python

import sys

if __name__ == "__main__":
  sys.path.append("/usr/share/ezweb-platform")

  from admintools.core import MainEzWebAdminTool
  admintool = MainEzWebAdminTool()
  admintool.execute()
  sys.exit(0)
