#!/usr/bin/python

import sys
import os

import string
from random import Random

import gettext
from gettext import gettext as _

import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
from optparse import OptionParser


def get_ezweb_connection(settings):
  conn = psycopg2.connect (host = settings["admin_host"],
                           user = settings["admin_user"],
                           password = 'postgressucks')
  conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
  return conn

def connect(settings):
  conn = psycopg2.connect (host = settings['database_host'],
                           user = settings['database_user'],
                           password = settings['database_pass'],
                           database = settings['database_name'])
  return conn

def get_settings(conf_name, action, options):
  if not options:
    options = {}

  settings = {}
  settings['database_host'] = "localhost"

  if options.database_user != None:
    settings['database_user'] = options.database_user
  elif os.environ.has_key('DATABASE_USER'):
    settings['database_user'] = os.environ['DATABASE_USER']
  else:
    settings['database_user'] = "ezweb-" + conf_name

  if options.database_name != None:
    settings['database_name'] = options.database_name
  if os.environ.has_key('DATABASE_NAME'):
    settings['database_name'] = os.environ['DATABASE_NAME']
  else:
    settings['database_name'] = "ezweb-" + conf_name

  if options.database_pass != None:
    settings['database_pass'] = options.database_pass
  elif os.environ.has_key('DATABASE_PASS'):
    settings['database_pass'] = os.environ['DATABASE_PASS']
  else:
    settings['database_pass'] = ''.join(Random().sample(string.letters+string.digits, 12))

  return settings

def print_settings(settings):
  print "DJANGO_DATABASE_ENGINE=postgresql_psycopg2"
  print "DATABASE_USER=" + settings['database_user']
  print "DATABASE_NAME=" + settings['database_name']
  print "DATABASE_PASS=" + settings['database_pass']
  print "DATABASE_OPTIONS="
  #print "DATABASE_HOST=" + settings['database_host']
  #print "DATABASE_PORT=" + settings['database_port']

def drop_db_if_exists(conn, settings):
  cursor.execute("SELECT 1 FROM pg_database WHERE datname='" + settings['database_name'] + "';")
  if cursor.rowcount == 0:
    cursor.execute("DROP DATABASE " + settings['database_name'] + ";")

def create_db(cursor, settings):
  cursor.execute("CREATE DATABASE \"" + settings['database_name'] + "\" OWNER \"" + settings['database_user'] + "\";")

if __name__ == "__main__":
  parser = OptionParser()
  parser.add_option ("--database-user","--database-user", action="store",
                     dest="database_user", help=_("Try to run a dist-upgrade"))
  parser.add_option ("--database-name","--database-name", action="store",
                     dest="database_name", help=_("Try to run a dist-upgrade"))
  parser.add_option ("--database-pass","--database-pass", action="store",
                     dest="database_pass", help=_("Try to run a dist-upgrade"))

  (options, args) = parser.parse_args()

  action = args[0]
  conf_name = args[1]

  settings = get_settings(conf_name, action, options)

  if action == "prepare":
    conn = get_ezweb_connection()
    cursor = conn.cursor()

    cursor.execute("SELECT 1 FROM pg_user WHERE usename = '" + settings['database_user'] + "';")
    if cursor.rowcount == 0:
      sys.stderr.write("  User " + settings['database_user'] + " doesn't exists.\n")
      cursor.execute("CREATE USER \"" + settings['database_user'] + "\" PASSWORD '" + settings['database_pass'] + "';")
      sys.stderr.write("  User " + settings['database_user'] + " created.\n")


    cursor.execute("SELECT 1 FROM pg_database WHERE datname='" + settings['database_name'] + "';")
    if cursor.rowcount == 0:
      sys.stderr.write("  Database " + settings['database_name'] + " doesn't exists.\n")
      create_db(cursor, settings)
      sys.stderr.write("  Database " + settings['database_name'] + " created.\n")

    print_settings(settings)

  elif action == "delete":
    conn = get_ezweb_connection()
    cursor = conn.cursor()
    drop_db_if_exists(conn, settings)

  elif action == "clear":
    conn = get_ezweb_connection()
    cursor = conn.cursor()
    drop_db_if_exists(conn, settings)
    create_db(cursor, settings)

  else:
    parser.print_help()

  sys.exit(0)