package mobi.mymem.event;

import mobi.mymem.MyOPs;
import mobi.mymem.MyUtils;

import org.morfeo.tidmobile.server.RequestData;
import org.morfeo.tidmobile.server.flow.IActionExecutor;
import org.morfeo.tidmobile.server.util.ContextUtil;

/* Java code generated by MyMobileWeb Plugin */
public class DefaultEventHandler {


}