/**
    -                    ***MyMobileWeb***
    - Java Script code generated by MyMobileWeb Generation Proccess
    - Date: Thu May 29 16:41:23 GMT+01:00 2008
**/

function _smt_npr_onsubmit_validate() { 

	// Add your custom code

	return true;
}
