package mobi.mymem.event.contacts;

import mobi.mymem.Constants;
import mobi.mymem.MyContextVariables;
import mobi.mymem.MyOAs;
import mobi.mymem.MyPresentations;
import mobi.mymem.MyUtils;

import org.morfeo.tidmobile.context.Context;
import org.morfeo.tidmobile.context.ContextScopes;
import org.morfeo.tidmobile.server.RequestData;
import org.morfeo.tidmobile.server.flow.IActionExecutor;

import ezWebAPI.EzWebAPI;


/* Java code generated by MyMobileWeb Plugin */
public class ContactsEventHandler {


	public void onInitOP(RequestData req, IActionExecutor act) throws Throwable {
		
		Context the_context = req.getContext();
		EzWebAPI API = null;
		
		try{
			API = (EzWebAPI) the_context.getElement("EzWebAPI");
			
			//get the location to show
			act.executeOA(MyOAs.LOCALIZEADDRESS, req);
			act.executeOA(MyOAs.CURSORS_CURSORS_OA, req);
			
			// set the back link href
			the_context.setElement(MyContextVariables.PLATFORM, Constants.PLATFORM, ContextScopes.APPLICATION_SCOPE);
			
			//show the map
			act.navigate(MyPresentations.CONTACTS_LOCALIZE, req);
		}
		catch (Exception e){
			//API not found
			//show error message
			System.out.println("Authentication error");
		}
		
		
	}
		
}