package mobi.mymem.event.contacts;


import mobi.mymem.MyContextVariables;
import mobi.mymem.MyOAs;
import mobi.mymem.MyPresentations;

import org.morfeo.tidmobile.context.Context;
import org.morfeo.tidmobile.server.RequestData;
import org.morfeo.tidmobile.server.flow.IActionExecutor;



/* Java code generated by MyMobileWeb Plugin */
public class LocalizeEventHandler {


public void cursors_onclick(RequestData req, IActionExecutor exec) throws Throwable {
		
		Context the_context = req.getContext();
		
		// Ejecutamos la OA que mapea el resultado de la elección
		if (the_context.getElement(MyContextVariables.CURSOR).equals("UP"))
			exec.executeOA(MyOAs.UPLOCALIZE, req);
		else if (the_context.getElement(MyContextVariables.CURSOR).equals("DO"))
			exec.executeOA(MyOAs.DOWNLOCALIZE, req);
		else if (the_context.getElement(MyContextVariables.CURSOR).equals("LE"))
			exec.executeOA(MyOAs.LEFTLOCALIZE, req);
		
		else if (the_context.getElement(MyContextVariables.CURSOR).equals("RI"))
			exec.executeOA(MyOAs.RIGTHLOCALIZE, req);
		
		else if (the_context.getElement(MyContextVariables.CURSOR).equals("IN"))
			exec.executeOA(MyOAs.ZOOMIN, req);
		else if (the_context.getElement(MyContextVariables.CURSOR).equals("IN2"))
		{
			exec.executeOA(MyOAs.ZOOMIN, req);
			exec.executeOA(MyOAs.ZOOMIN, req);
		}
		
		else if (the_context.getElement(MyContextVariables.CURSOR).equals("OUT"))
			exec.executeOA(MyOAs.ZOOMOUT, req);
		else if (the_context.getElement(MyContextVariables.CURSOR).equals("OUT2"))
		{
			exec.executeOA(MyOAs.ZOOMOUT, req);
			exec.executeOA(MyOAs.ZOOMOUT, req);
		}
		
		else if (the_context.getElement(MyContextVariables.CURSOR).equals("CE"))
			exec.executeOA(MyOAs.CENTER, req);
		

		exec.executeOA(MyOAs.LOCALIZEADDRESS, req);
		
		//clean the selected element and navigate to the presentation
		the_context.removeElement(MyContextVariables.CURSOR);
		exec.navigate(MyPresentations.CONTACTS_LOCALIZE, req);
	}
	
public void cursorsmobile_onclick(RequestData req, IActionExecutor exec) throws Throwable {
	
	
	Context the_context = req.getContext();
	String cursor_mobile = (String) the_context.getElement(MyContextVariables.CURSORMOBILE);
	//String menuOption = (String) myContext.getElement(MyContextVariable.VAR_OPC_MENU);

	if (cursor_mobile.equals("UP"))
		exec.executeOA(MyOAs.UPLOCALIZE, req);
	else if (cursor_mobile.equals("DO"))
		exec.executeOA(MyOAs.DOWNLOCALIZE, req);
	else if (cursor_mobile.equals("LE"))
		exec.executeOA(MyOAs.LEFTLOCALIZE, req);
	
	else if (cursor_mobile.equals("RI"))
		exec.executeOA(MyOAs.RIGTHLOCALIZE, req);
	
	else if (cursor_mobile.equals("IN"))
		exec.executeOA(MyOAs.ZOOMIN, req);
	else if (cursor_mobile.equals("IN2"))
	{
		exec.executeOA(MyOAs.ZOOMIN, req);
		exec.executeOA(MyOAs.ZOOMIN, req);
	}
	
	else if (cursor_mobile.equals("OUT"))
		exec.executeOA(MyOAs.ZOOMOUT, req);
	else if (cursor_mobile.equals("OUT2"))
	{
		exec.executeOA(MyOAs.ZOOMOUT, req);
		exec.executeOA(MyOAs.ZOOMOUT, req);
	}
	
	else if (cursor_mobile.equals("CE"))
		exec.executeOA(MyOAs.CENTER, req);


	exec.executeOA(MyOAs.LOCALIZEADDRESS, req);
	
	//clean the selected element and navigate to the presentation
	the_context.removeElement(MyContextVariables.CURSOR);
	exec.navigate(MyPresentations.CONTACTS_LOCALIZE, req);
	

}

}