package mobi.mymem.event.includes;

import org.morfeo.tidmobile.server.RequestData;
import org.morfeo.tidmobile.server.flow.IActionExecutor;

/* Java code generated by MyMobileWeb Plugin */
public class FootEventHandler {


public void exampleMenu_onclick(RequestData req, IActionExecutor act) throws Throwable {
act.showMessage("Don't implemented", req);
 }

}