package mobi.mymem.event.includes;

import org.morfeo.tidmobile.server.RequestData;
import org.morfeo.tidmobile.server.flow.IActionExecutor;

/* Java code generated by MyMobileWeb Plugin */
public class IncludesEventHandler {


public void onInitOP(RequestData req, IActionExecutor act) throws Throwable {
 }

}