/**
    -                    ***MyMobileWeb***
    - Java Script code generated by MyMobileWeb Generation Proccess
    - Date: Fri May 30 10:42:59 GMT+01:00 2008
    - Note: DO NOT TOUCH
**/

function _smt_npr_onsubmit_gen_validate() { 

 // Validate control: seAsMe_VAL
 if(document.forms[0].seAsMe_VAL) {

 }

 if(typeof _smt_npr_onsubmit_validate == 'function') { var result = _smt_npr_onsubmit_validate(); } 


 if ( result ) return true;
 else return false;

}
