/**
    -                    ***MyMobileWeb***
    - Java Script code generated by MyMobileWeb Generation Proccess
    - Date: Tue Jun 17 08:31:59 GMT+01:00 2008
    - Note: DO NOT TOUCH
**/

function _smt_npr_onsubmit_gen_validate() { 

 // Validate control: Minute_VAL
 if(document.forms[0].Minute_VAL) {

 }

 // Validate control: Hour_VAL
 if(document.forms[0].Hour_VAL) {

 }

 // Validate control: ChaTimField_VAL
 if(document.forms[0].ChaTimField_VAL) {

 }

 // Validate control: Second_VAL
 if(document.forms[0].Second_VAL) {

 }

 if(typeof _smt_npr_onsubmit_validate == 'function') { var result = _smt_npr_onsubmit_validate(); } 


 if ( result ) return true;
 else return false;

}
