/**
    -                    ***MyMobileWeb***
    - Java Script code generated by MyMobileWeb Generation Proccess
    - Date: Tue Jun 17 08:31:59 GMT+01:00 2008
    - Note: DO NOT TOUCH
**/

function _smt_npr_onsubmit_gen_validate() { 

 // Validate control: Day_VAL
 if(document.forms[0].Day_VAL) {

 }

 // Validate control: Year_VAL
 if(document.forms[0].Year_VAL) {

 }

 // Validate control: ChaDatField_VAL
 if(document.forms[0].ChaDatField_VAL) {

 }

 // Validate control: Month_VAL
 if(document.forms[0].Month_VAL) {

 }

 if(typeof _smt_npr_onsubmit_validate == 'function') { var result = _smt_npr_onsubmit_validate(); } 


 if ( result ) return true;
 else return false;

}
