/**
    -                    ***MyMobileWeb***
    - Java Script code generated by MyMobileWeb Generation Proccess
    - Date: Tue Jun 17 08:31:59 GMT+01:00 2008
    - Note: DO NOT TOUCH
**/

var msg = new Message();

function getMessage(id) {

 return msg.getMsg(id)

}

function getMs (id){

 return eval ('this.'+ id);

}

// My Object Message
function Message(){

  this.MyMobileWeb_E_No_User = "Introduzca el usuario";

  this.MyMobileWeb_E_No_Pass = "Introduzca la contraseña";

  this.MyMobileWeb_E_Invalid_Login = "Usuario y/o Contraseña no válidos. Reintente";

  this.MyMobileWeb_E_Required = "{0} es obligatorio";

  this.MyMobileWeb_E_Int = "{0} debe ser un número entero";

  this.MyMobileWeb_E_Int_Range = "{0} debe ser un número entero entre {1} y {2}";

  this.MyMobileWeb_E_Int_Range_2 = "{0} debe ser un número entero mayor que {1}";

  this.MyMobileWeb_E_Int_Range_3 = "{0} debe ser un número entero menor que {1}";

  this.MyMobileWeb_E_Float = "{0} debe ser un número";

  this.MyMobileWeb_E_Float_Range = "{0} debe ser un número entre {1} y {2}";

  this.MyMobileWeb_E_Float_Range_2 = "{0} debe ser un número mayor que {1}";

  this.MyMobileWeb_E_Float_Range_3 = "{0} debe ser un número menor que {1}";

  this.MyMobileWeb_E_Date = "{0} debe ser una fecha con formato {1}";

  this.MyMobileWeb_E_Date_Range = "{0} debe ser una fecha entre {1} y {2}";

  this.MyMobileWeb_E_Date_Range_2 = "{0} debe ser una fecha posterior a {1}";

  this.MyMobileWeb_E_Date_Range_3 = "{0} debe ser una fecha anterior a {1}";

  this.MyMobileWeb_E_Time = "{0} debe ser una hora con formato {1}";

  this.MyMobileWeb_E_Time_Range = "{0} debe ser una hora entre {1} y {2}";

  this.MyMobileWeb_E_Time_Range_2 = "{0} debe ser una hora posterior a {1}";

  this.MyMobileWeb_E_Time_Range_3 = "{0} debe ser una hora anterior a {1}";

  this.MyMobileWeb_E_Format = "{0} no tiene un formato correcto";

  this.MyMobileWeb_E_Length = "{0} debe tener longitud {1}";

  this.MyMobileWeb_E_Min_Length = "La longitud mínima de {0} es {1}";

  this.MyMobileWeb_E_Max_Length = "La longitud máxima de {0} es {1}";

  this.MyMobileWeb_E_Min_Max_Length = "La longitud mínima de {0} es {1} y la máxima es {2}";

  this.MyMobileWeb_E_Inv_Profile = "El usuario {0} no tiene un perfil válido para entrar en la aplicación";

  this.MyMobileWeb_E_UnExp_Error = "Excepción no esperada: {0}";

  this.MyMobileWeb_E_File_Size = "El tamaño máximo de {0} es {1}";

  this.MyMobileWeb_E_File_ContentType = "El content type de {0} debe ser {1}";

  this.MyMobileWeb_Choose_One = "Seleccione";

  this.getMsg=getMs;

}
/**
    -             *** MyMobileWeb ***
    - Java Script code created by MyMobileWeb Group
    - Date: Wed Jun 22 09:21:58 CEST 2005
    - Note: DO NOT TOUCH
**/

// Parameter is integer ?

function isInteger(s){
	
    var i;
    for (i = 0; i < s.length; i++){           
        var c = s.charAt(i);
        if (((c < "0") || (c > "9"))) return false;
    }
    // All characters are numbers.
    return true;
}

function isFloat(s){
	
    var i;
    for (i = 0; i < s.length; i++){           
        var c = s.charAt(i);
        if (((c < "0") || (c > "9"))){
        	if (c != ".") return false;
        }
    }
    // All characters are numbers or dot.
    return true;
}

// Change in s x --> y.

function change(template, x, y) {  
  
  var first = template.substring(0, template.indexOf(x));    
  var second = template.substring(template.indexOf(x) + x.length, template.length);  
  return first + y + second;
  
}


/** Substitution in template:
    -   parameters {0}, {1}, {2},.. --> parameters[0], parameters[1], parameters[2],..
**/
function messageFormat (template, parameters){

    var out = template;
        
    for (i=0 ; i<parameters.length ; i++) { 
        var temp = '{' + i + '}';                
        out = change (out,temp,parameters[i]);
    }
    
    return out;
}


// Execute trim() function on a string

function trim(s) {
  while (s.substring(0,1) == ' ') {
    s = s.substring(1,s.length);
  }
  while (s.substring(s.length-1,s.length) == ' ') {
    s = s.substring(0,s.length-1);
  }
  return s;
}
