/**
    -                    ***MyMobileWeb***
    - Java Script code generated by MyMobileWeb Generation Proccess
    - Date: Fri May 30 10:43:00 GMT+01:00 2008
    - Note: DO NOT TOUCH
**/

function _smt_npr_onsubmit_gen_validate() { 

 if(typeof _smt_npr_onsubmit_validate == 'function') { var result = _smt_npr_onsubmit_validate(); } 


 if ( result ) return true;
 else return false;

}
